name: Branch
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - '**' # Push events on all branches

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  AWS_DEFAULT_REGION: eu-west-2
  S3_BUCKET: dev-uk-websites
  REACT_APP_GAME_TYPE: 'gametemplate'

jobs:
  ig:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [14]

    env:
      BRAND_ID: ig
      ENV: dev

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        env:
          NODE_ENV: development
          CI: false #to avoid warnings for now.
          REACT_APP_SITE_ID: '00000000'
          REACT_APP_GA_TRACKING_CODE: UA-81856875-11
          REACT_APP_NAME: Game template
          REACT_APP_ID: virtual-league
        run: |
          npm ci
          cd ./src && ln -s brands/$BRAND_ID theme && cd ../
          npm run build --if-present
          #npm test
      - name: Sync files to S3
        run: |
          echo $GITHUB_REPOSITORY
          export REPO=`echo $GITHUB_REPOSITORY | sed 's/^incentivegames\///'`
          echo $GITHUB_REF
          export TAG=`echo $GITHUB_REF | sed 's/^refs\/heads\///'`
          if [ $TAG = "master" ]; then export TAG=latest; fi
          echo "$REPO:$TAG"
          if [ $TAG = "latest" ]; then
            echo "Synching to $S3_BUCKET..."
            aws s3 sync ./build/ s3://$S3_BUCKET/$BRAND_ID/$REACT_APP_GAME_TYPE/$TAG --delete
          else
            echo "Not deploying for $TAG"
          fi
